"""Compiler-robust Hopf differential-frame research utilities."""

from .compiler_boundaries import (
    CheckpointInterfaceSafeExample,
    CheckpointStateColumnCounterexample,
    GlobalStateColumnCounterexample,
    two_qubit_checkpoint_interface_safe_example,
    two_qubit_checkpoint_state_column_counterexample,
    two_qubit_global_state_column_counterexample,
)
from .frames import complex_frame_matrix, real_frame_matrix
from .resource_bounds import (
    generic_all_column_cqsp_size_proxy,
    lightcone_depth_lower_bound,
    lightcone_parameter_slots,
    low_workspace_absorption_holds,
    parameter_count_depth_lower_bound,
    real_state_parameter_dimension,
    routed_geometric_inequality_holds,
)
from .tree_decoder import (
    ConditionedPrefixResourceRow,
    ReversibleGate,
    TreeDecoderLayout,
    TreeDecoderResourceRow,
    binary_to_unary_operations,
    conditioned_prefix_resource_row,
    tree_decoder_resource_row,
    unary_hopf_code_action,
)
from .tree_structure import (
    conditioned_prefix_frame,
    reconstructed_frame,
    subtree_angle_indices,
    tail_block_diagonal_frame,
)
from .unified_compiler import (
    DiagonalUCGResourceRow,
    DirectFrameResourceRow,
    RouteWorkspaceRow,
    UnifiedComplexResourceRow,
    UnifiedFrameResourceRow,
    choose_routed_cut,
    controlled_unitary,
    diagonal_ucg_matrix,
    diagonal_ucg_resource_row,
    direct_frame_resource_row,
    route_workspace_row,
    unified_complex_frame_resource_row,
    unified_cut_frame_matrix,
    unified_real_frame_resource_row,
)

__all__ = [
    "CheckpointInterfaceSafeExample",
    "CheckpointStateColumnCounterexample",
    "ConditionedPrefixResourceRow",
    "DiagonalUCGResourceRow",
    "DirectFrameResourceRow",
    "GlobalStateColumnCounterexample",
    "ReversibleGate",
    "RouteWorkspaceRow",
    "TreeDecoderLayout",
    "TreeDecoderResourceRow",
    "UnifiedComplexResourceRow",
    "UnifiedFrameResourceRow",
    "binary_to_unary_operations",
    "choose_routed_cut",
    "complex_frame_matrix",
    "conditioned_prefix_frame",
    "conditioned_prefix_resource_row",
    "controlled_unitary",
    "diagonal_ucg_matrix",
    "diagonal_ucg_resource_row",
    "direct_frame_resource_row",
    "generic_all_column_cqsp_size_proxy",
    "lightcone_depth_lower_bound",
    "lightcone_parameter_slots",
    "low_workspace_absorption_holds",
    "parameter_count_depth_lower_bound",
    "real_frame_matrix",
    "real_state_parameter_dimension",
    "reconstructed_frame",
    "route_workspace_row",
    "routed_geometric_inequality_holds",
    "subtree_angle_indices",
    "tail_block_diagonal_frame",
    "tree_decoder_resource_row",
    "two_qubit_checkpoint_interface_safe_example",
    "two_qubit_checkpoint_state_column_counterexample",
    "two_qubit_global_state_column_counterexample",
    "unary_hopf_code_action",
    "unified_complex_frame_resource_row",
    "unified_cut_frame_matrix",
    "unified_real_frame_resource_row",
]

__version__ = "0.2.0a0"
