#!/usr/bin/env python3
"""Run bounded CP28 evidence and compare its deterministic scientific receipts.

Requires only Python 3.10+ and the sibling verification/fault_tolerant directory.
Saved expected receipts are never regenerated by this command.
"""

import argparse
import ast
from hashlib import sha256
import json
from pathlib import Path
import subprocess
import sys
from tempfile import TemporaryDirectory
from time import perf_counter


ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "verification" / "fault_tolerant"
SUITES = (
    "gray_geometric_checks",
    "shift_kernel_checks",
    "shift_resource_checks",
    "geometric_reflection_checks",
)
PROVENANCE_FIELDS = {"source_sha256", "helper_sha256"}


def digest(path):
    return sha256(path.read_bytes()).hexdigest()


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def scientific_receipt(receipt):
    """Remove relocated-source hashes only, retaining every scientific digest."""
    return {key: value for key, value in receipt.items() if key not in PROVENANCE_FIELDS}


def scientific_digest(receipt):
    encoded = json.dumps(scientific_receipt(receipt), sort_keys=True, separators=(",", ":"))
    return sha256(encoded.encode()).hexdigest()


def verify_provenance():
    manifest = json.loads((EVIDENCE / "PROVENANCE.json").read_text())
    for field, directory in (("local_sources_sha256", EVIDENCE),
                             ("expected_receipts_sha256", EVIDENCE / "expected")):
        for name, expected in manifest[field].items():
            require(Path(name).name == name, "provenance filenames must be local basenames")
            require(digest(directory / name) == expected, f"provenance mismatch: {directory / name}")
    require(set(manifest["expected_receipts_sha256"]) == {name + ".json" for name in SUITES},
            "expected receipt manifest must cover exactly the four imported suites")
    require(set(manifest["local_sources_sha256"]) == {path.name for path in EVIDENCE.glob("*.py")},
            "source manifest must cover the complete local Python dependency closure")
    text = (EVIDENCE / "exact_arithmetic.py").read_text()
    classes = {node.name: node for node in ast.parse(text).body if isinstance(node, ast.ClassDef)}
    for extraction in manifest["arithmetic_extractions"]:
        node = classes[extraction["class"]]
        start = min([node.lineno] + [item.lineno for item in node.decorator_list])
        source = "\n".join(text.splitlines()[start - 1:node.end_lineno])
        require(sha256(source.encode()).hexdigest() == extraction["class_text_sha256"],
                f"verbatim arithmetic extraction changed: {node.name}")
    return manifest


def verify_receipt_sources(name, receipt):
    sources = receipt["source_sha256"]
    if isinstance(sources, str):
        sources = {name + ".py": sources}
    if "helper_sha256" in receipt:
        sources = dict(sources)
        sources["geometric_reflection_checks.py"] = receipt["helper_sha256"]
    for filename, expected in sources.items():
        require(Path(filename).name == filename, "receipt source names must be local basenames")
        require(digest(EVIDENCE / filename) == expected, f"generated source receipt mismatch: {filename}")


def first_difference(expected, actual, path="$"):
    if type(expected) is not type(actual):
        return path + "type differs"
    if isinstance(expected, dict):
        if expected.keys() != actual.keys():
            return path + "keys differ"
        for key in expected:
            if expected[key] != actual[key]:
                return first_difference(expected[key], actual[key], path + "." + key)
    elif isinstance(expected, list):
        if len(expected) != len(actual):
            return path + "length differs"
        for index, (left, right) in enumerate(zip(expected, actual)):
            if left != right:
                return first_difference(left, right, path + f"[{index}]")
    return path + "value differs"


def verify_output_path(output, protected):
    require(protected not in output.resolve().parents and output.resolve() != protected,
            "output must not resolve to a tracked expected fixture")
    require(not output.is_symlink(), "output files must not be symbolic links")
    require(not output.exists() or output.stat().st_nlink == 1,
            "output files must not have hard links")


def run_suites(output_dir, timeout):
    manifest = verify_provenance()
    output_dir = output_dir.resolve()
    protected = (EVIDENCE / "expected").resolve()
    require(output_dir != protected and protected not in output_dir.parents,
            "--output-dir cannot be the tracked expected-fixture directory")
    output_dir.mkdir(parents=True, exist_ok=True)
    # Preflight every destination before a suite can write through an existing
    # link. Path.resolve alone cannot detect hard links to tracked fixtures.
    for filename in [name + ".json" for name in SUITES] + ["verification_summary.json"]:
        verify_output_path(output_dir / filename, protected)
    rows = []
    for name in SUITES:
        output = output_dir / (name + ".json")
        verify_output_path(output, protected)
        started = perf_counter()
        process = subprocess.run(
            [sys.executable, "-B", str(EVIDENCE / (name + ".py")), "--output", str(output)],
            cwd=output_dir, capture_output=True, text=True, timeout=timeout,
        )
        if process.returncode:
            raise RuntimeError(f"{name} failed ({process.returncode}):\n{process.stdout}{process.stderr}")
        require(output.is_file(), f"{name} did not write its receipt")
        actual = json.loads(output.read_text())
        expected = json.loads((protected / output.name).read_text())
        require(actual.get("status") == "passed", f"{name} did not report passed")
        verify_receipt_sources(name, actual)
        wanted, observed = scientific_receipt(expected), scientific_receipt(actual)
        require(json.dumps(wanted, sort_keys=True) == json.dumps(observed, sort_keys=True),
                f"{name} scientific fixture mismatch: {first_difference(wanted, observed)}")
        elapsed = round(perf_counter() - started, 3)
        rows.append({"suite": name, "status": "passed", "elapsed_seconds": elapsed,
                     "scientific_sha256": scientific_digest(actual),
                     "expected_receipt_sha256": manifest["expected_receipts_sha256"][output.name]})
        print(f"PASS {name}: scientific receipt matches ({elapsed:.3f}s)", flush=True)
    require(verify_provenance() == manifest, "sources or tracked expected fixtures changed during the run")
    report = {"status": "passed", "python": sys.version.split()[0], "suites": rows,
              "source_sha256": manifest["local_sources_sha256"],
              "comparison": "Exact parsed JSON equality except top-level source_sha256/helper_sha256; current source hashes independently verified.",
              "scope": "Finite exact algebra and emitted logical Gray gates, scalar resource proxies, and supporting source-reflection fixtures; not an end-to-end compiler or an asymptotic theorem proof."}
    summary = output_dir / "verification_summary.json"
    verify_output_path(summary, protected)
    summary.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, help="retain generated receipts here; default uses a temporary directory")
    parser.add_argument("--timeout", type=float, default=300, help="seconds allowed per suite (default: 300)")
    args = parser.parse_args()
    if sys.version_info < (3, 10):
        parser.error("Python 3.10 or newer is required")
    if args.timeout <= 0:
        parser.error("--timeout must be positive")
    try:
        if args.output_dir is None:
            with TemporaryDirectory(prefix="hopf-fault-tolerant-") as directory:
                report = run_suites(Path(directory), args.timeout)
        else:
            report = run_suites(args.output_dir, args.timeout)
        print(f"PASS fault-tolerant verification: {len(report['suites'])} suites; expected fixtures preserved")
        return 0
    except (AssertionError, OSError, ValueError, RuntimeError, subprocess.TimeoutExpired) as error:
        print(f"FAIL fault-tolerant verification: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
